# This is a basic workflow to help you get started with Actions

name: Prod - Deploy to S3

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    environment: Prod
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        env:
          VUE_APP_AUTH0_CONFIG_CALLBACKURL: ${{ secrets.VUE_APP_AUTH0_CONFIG_CALLBACKURL }}
          VUE_APP_DOMAINURL: ${{ secrets.VUE_APP_DOMAINURL }}
          VUE_APP_AUTH0_CONFIG_AUD: ${{ secrets.VUE_APP_AUTH0_CONFIG_AUD }}
          VUE_APP_AUTH0_CONFIG_CLIENTID: ${{ secrets.VUE_APP_AUTH0_CONFIG_CLIENTID }}
          VUE_APP_AUTH0_CONFIG_DOMAIN: ${{ secrets.VUE_APP_AUTH0_CONFIG_DOMAIN }}
          VUE_APP_AUTH0_CONFIG_DOMAINURL: ${{ secrets.VUE_APP_AUTH0_CONFIG_DOMAINURL }}
          VUE_APP_AUTH0_CONFIG_RESPONSETYPE: ${{ secrets.VUE_APP_AUTH0_CONFIG_RESPONSETYPE }}
          VUE_APP_AUTH0_CONFIG_SCOPE: ${{ secrets.VUE_APP_AUTH0_CONFIG_SCOPE }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
          VUE_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENT_ID }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_PUBLIC_KEY: ${{ secrets.VUE_APP_FIREBASE_PUBLIC_KEY }}  
          VUE_APP_FIREBASE_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_SENDER_ID }}  
          VUE_APP_GRAPHQL_CLIENT: ${{ secrets.VUE_APP_GRAPHQL_CLIENT }}
          VUE_APP_SITE_NAME: Prod
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
